### PR TITLE
chore: Delete .DS_Store file

### PR DESCRIPTION
**Pull request by haoxins**
#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional):

### CODE REVIEW

**Review by haoxins — COMMENTED** [review]
chore: delete and ignore the .DS_Store file

**Comment by AsterDY** [comment]
why??

**Comment by haoxins** [comment]
> why??

not something big, just the convention to ignore the MacOS's `.DS_Store`.
feel free to close it 😂

**Review by xiaost — APPROVED** [review]

**Comment by AsterDY** [comment]
o

> > why??
> 
> not something big, just the convention to ignore the MacOS's `.DS_Store`. feel free to close it 😂

oh, I misunderstood. It's an useful PR. Thx! @haoxins

**Pull request merged**
